# Generated by Django 5.2.4 on 2025-11-27 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='report',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='report',
            name='time_spent',
            field=models.DurationField(blank=True, null=True, verbose_name='Tiempo total'),
        ),
    ]
