# Generated by Django 5.2.4 on 2025-07-21 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.TimeField()),
                ('status', models.BooleanField(default=False)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.buildings')),
                ('technician', models.ForeignKey(limit_choices_to={'groups__name': 'Técnico'}, on_delete=django.db.models.deletion.CASCADE, related_name='technician_schedules', to=settings.AUTH_USER_MODEL)),
                ('tower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.towers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_schedules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
