# Generated by Django 5.2.4 on 2025-07-25 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='building',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='user',
        ),
        migrations.AddField(
            model_name='schedule',
            name='client',
            field=models.ForeignKey(default=2, limit_choices_to={'groups__name': 'Cliente'}, on_delete=django.db.models.deletion.CASCADE, related_name='client_schedules', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
