# Generated by Django 5.2.4 on 2025-08-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_remove_schedule_building_remove_schedule_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='recurrence',
            field=models.CharField(choices=[('single', 'Individual'), ('monthly', 'Mensual')], default='single', max_length=20),
        ),
    ]
