# Generated by Django 5.2.4 on 2025-11-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_schedule_recurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='type_schedule',
            field=models.CharField(choices=[('programado', 'Agendamiento programado'), ('no_programado', 'Agendamiento no programado')], default='programado', max_length=20),
        ),
    ]
