# Generated by Django 5.2.4 on 2025-11-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_schedule_type_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='type_schedule',
            field=models.CharField(choices=[('scheduled', 'Programado'), ('unscheduled', 'No programado')], default='programado', max_length=20),
        ),
    ]
