# Generated by Django 5.2.4 on 2025-11-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_alter_schedule_type_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='type_schedule',
            field=models.CharField(choices=[('scheduled', 'Agendamiento Programado'), ('unscheduled', 'No programado')], default='scheduled', max_length=20),
        ),
    ]
