# Generated by Django 5.2.4 on 2025-11-21 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_alter_schedule_type_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='type_schedule',
        ),
    ]
