# Generated by Django 5.2.4 on 2025-11-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_remove_schedule_type_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='programmed',
            field=models.CharField(choices=[('programmed', 'Programado'), ('not_programmed', 'No programado')], default='programmed', max_length=20),
        ),
    ]
