# Generated by Django 5.2.4 on 2025-11-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_schedule_programmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('complete', 'Realizado'), ('in_production', 'En producción'), ('to_be_done', 'Por realizar')], default='por_realizar', max_length=20),
        ),
    ]
