# Generated by Django 5.2.4 on 2025-11-26 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_alter_schedule_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('to_be_done', 'Por realizar'), ('in_production', 'En producción'), ('complete', 'Realizado')], default='por_realizar', max_length=20),
        ),
    ]
