# Generated by Django 5.2.4 on 2025-08-19 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='replacementParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameItem', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('approved', models.BooleanField(default=False)),
                ('status_Install', models.CharField(choices=[('por_instalar', 'Por instalar'), ('instalado', 'Instalado')], default='por_instalar', max_length=20)),
                ('status_Payment', models.CharField(choices=[('pagado', 'Pagado'), ('falta_pago', 'Falta de pago')], default='falta_pago', max_length=20)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos', to=settings.AUTH_USER_MODEL)),
                ('tower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos', to='buildings.towers')),
            ],
        ),
    ]
