# Generated by Django 5.2.4 on 2025-10-31 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replacementParts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replacementparts',
            name='approved',
        ),
        migrations.AddField(
            model_name='replacementparts',
            name='approved_status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
    ]
