# Generated by Django 5.2.4 on 2025-11-17 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replacementParts', '0002_remove_replacementparts_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replacementparts',
            name='status_Install',
            field=models.CharField(choices=[('por_instalar', 'Pendiente por instalar'), ('instalado', 'Instalado')], default='por_instalar', max_length=20),
        ),
    ]
