# Generated by Django 5.2.4 on 2025-11-17 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replacementParts', '0003_alter_replacementparts_status_install'),
    ]

    operations = [
        migrations.AddField(
            model_name='replacementparts',
            name='cantidad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='replacementparts',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='replacementparts',
            name='numero_cotizacion',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='replacementparts',
            name='precio_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='replacementparts',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
