# Generated by Django 5.2.4 on 2025-11-17 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replacementParts', '0004_replacementparts_cantidad_replacementparts_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replacementparts',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='replacementparts',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='replacementparts',
            name='numero_cotizacion',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='replacementparts',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='replacementparts',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
