# Generated by Django 5.2.4 on 2025-11-18 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('replacementParts', '0005_alter_replacementparts_cantidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replacementparts',
            name='price',
        ),
    ]
