# Generated by Django 5.2.4 on 2025-11-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replacementParts', '0006_remove_replacementparts_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replacementparts',
            name='status_Payment',
            field=models.CharField(choices=[('no_aplica', 'No aplica'), ('pendiente_anticipo', 'Pendiente anticipo')], default='falta_pago', max_length=20),
        ),
    ]
