# Generated by Django 5.2.4 on 2025-11-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replacementParts', '0007_alter_replacementparts_status_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replacementparts',
            name='status_Payment',
            field=models.CharField(choices=[('no_aplica', 'No aplica'), ('pendiente_anticipo', 'Pendiente anticipo')], default='no_aplica', max_length=20),
        ),
    ]
